// lib/data/rubric_map.dart

/// This file contains mapping of rubric categories used in Homeonix
/// Structure follows standard homeopathic repertory sections.
/// Used by: Symptom Analyzer, Remedy Finder, Category UI display

const Map<String, String> rubricMap = {
  "MIND AND DISPOSITION": "mind",
  "SENSORIUM": "sensorium",
  "INNER HEAD": "inner_head",
  "OUTER HEAD": "outer_head",
  "EYES": "eyes",
  "EARS": "ears",
  "NOSE": "nose",
  "UPPER FACE": "upper_face",
  "TEETH AND GUMS": "teeth_and_gums",
  "TASTE AND TONGUE": "taste_and_tongue",
  "INNER MOUTH": "inner_mouth",
  "THROAT": "throat",
  "EATING AND DRINKING": "eating_and_drinking",
  "APPETITE, THIRST, DESIRES, AVERSIONS": "appetite_and_desires",
  "HICCOUGH, BELCHING, NAUSEA AND VOMITING": "hiccough_belching_nausea",
  "SCROBICULUM AND STOMACH": "scrobiculum_and_stomach",
  "HYPOCHONDRIA": "hypochondria",
  "ABDOMEN": "abdomen",
  "STOOL AND RECTUM": "stool_and_rectum",
  "URINARY ORGANS": "urinary_organs",
  "MALE SEXUAL ORGANS": "male_sexual_organs",
  "FEMALE SEXUAL ORGANS": "female_sexual_organs",
  "PREGNANCY, PARTURITION, LACTATION": "pregnancy_parturition_lactation",
  "VOICE, LARYNX, TRACHEA AND BRONCHIA": "voice_larynx_trachea",
  "RESPIRATION": "respiration",
  "COUGH AND EXPECTORATION": "cough_and_expectoration",
  "INNER CHEST AND LUNGS": "inner_chest_and_lungs",
  "HEART, PULSE AND CIRCULATION": "heart_pulse_circulation",
  "OUTER CHEST": "outer_chest",
  "NECK AND BACK": "neck_and_back",
  "LOWER LIMBS": "lower_limbs",
  "REST, POSITION, MOTION": "rest_position_motion",
  "NERVES": "nerves",
  "SLEEP": "sleep",
  "DREAM": "dream",
  "TIME": "time",
  "TEMPERATURE AND WEATHER": "temperature_and_weather",
  "FEVER": "fever",
  "ATTACKS, PERIODICITY": "attacks_periodicity",
  "LOCALITY AND DIRECTION": "locality_and_direction",
  "SENSATIONS IN GENERAL": "sensations_in_general",
  "TISSUES": "tissues",
  "TOUCH, PASSIVE MOTION, INJURIES": "touch_passive_injuries",
  "SKIN": "skin",
  "STAGES OF LIFE AND CONSTITUTION": "life_stages_constitution",
  "DRUG RELATIONSHIP": "drug_relationship",
};