name: Flutter CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.0'  # Dart 3.6.0+ supported

      - name: Enable Flutter stable channel and upgrade
        run: |
          flutter channel stable
          flutter upgrade

      - name: Check Flutter version
        run: flutter --version

      - name: Clean Flutter Pub Cache
        run: flutter pub cache repair || true

      - name: Install dependencies
        run: flutter pub get

      - name: Analyze code
        run: flutter analyze

      - name: Accept Android Licenses
        run: yes | flutter doctor --android-licenses

      - name: Run tests
        run: flutter test

      - name: Build APK
        run: flutter build apk --release
